import type {
  User,
  Agent,
  Ticket,
  Category,
  Comment,
  TicketStatus,
  TicketPriority,
} from '@/types';

export const mockUsers: User[] = [
  {
    id: 'usr-001',
    email: 'john.doe@example.com',
    firstName: 'John',
    lastName: 'Doe',
    role: 'USER',
    createdAt: '2025-01-15T09:00:00Z',
  },
  {
    id: 'usr-002',
    email: 'jane.smith@example.com',
    firstName: 'Jane',
    lastName: 'Smith',
    role: 'USER',
    createdAt: '2025-02-20T09:00:00Z',
  },
  {
    id: 'usr-003',
    email: 'agent.mike@example.com',
    firstName: 'Mike',
    lastName: 'Johnson',
    role: 'SUPPORT_AGENT',
    createdAt: '2024-11-10T09:00:00Z',
  },
  {
    id: 'usr-004',
    email: 'agent.sarah@example.com',
    firstName: 'Sarah',
    lastName: 'Williams',
    role: 'SUPPORT_AGENT',
    createdAt: '2024-12-05T09:00:00Z',
  },
  {
    id: 'usr-005',
    email: 'admin@helpdesk.com',
    firstName: 'Admin',
    lastName: 'Root',
    role: 'ADMIN',
    createdAt: '2024-10-01T09:00:00Z',
  },
];

export const mockAgents: Agent[] = [
  {
    id: 'agt-001',
    userId: 'usr-003',
    firstName: 'Mike',
    lastName: 'Johnson',
    email: 'agent.mike@example.com',
    role: 'SUPPORT_AGENT',
    activeTickets: 4,
    resolvedTickets: 127,
    status: 'BUSY',
    createdAt: '2024-11-10T09:00:00Z',
  },
  {
    id: 'agt-002',
    userId: 'usr-004',
    firstName: 'Sarah',
    lastName: 'Williams',
    email: 'agent.sarah@example.com',
    role: 'SUPPORT_AGENT',
    activeTickets: 2,
    resolvedTickets: 89,
    status: 'AVAILABLE',
    createdAt: '2024-12-05T09:00:00Z',
  },
];

export const mockCategories: Category[] = [
  {
    id: 'cat-001',
    name: 'GENERAL',
    description: 'General inquiries and questions',
    ticketCount: 12,
  },
  {
    id: 'cat-002',
    name: 'TECHNICAL',
    description: 'Technical issues and problems',
    ticketCount: 34,
  },
  {
    id: 'cat-003',
    name: 'BILLING',
    description: 'Billing and payment related issues',
    ticketCount: 8,
  },
  {
    id: 'cat-004',
    name: 'ACCOUNT',
    description: 'Account access and configuration',
    ticketCount: 15,
  },
  {
    id: 'cat-005',
    name: 'BUG_REPORT',
    description: 'Software bug reports',
    ticketCount: 21,
  },
  {
    id: 'cat-006',
    name: 'FEATURE_REQUEST',
    description: 'New feature suggestions',
    ticketCount: 7,
  },
];

const now = new Date().toISOString();
const daysAgo = (n: number) => {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString();
};

export const mockComments: Comment[] = [
  {
    id: 'cmt-001',
    ticketId: 'tkt-001',
    authorId: 'usr-001',
    authorName: 'John Doe',
    authorRole: 'USER',
    body: 'I encountered this issue while trying to log in this morning. The error appears consistently.',
    createdAt: daysAgo(5),
  },
  {
    id: 'cmt-002',
    ticketId: 'tkt-001',
    authorId: 'usr-003',
    authorName: 'Mike Johnson',
    authorRole: 'SUPPORT_AGENT',
    body: 'Thanks for reporting this. I have been able to reproduce the issue and am investigating the root cause.',
    createdAt: daysAgo(4),
  },
  {
    id: 'cmt-003',
    ticketId: 'tkt-001',
    authorId: 'usr-003',
    authorName: 'Mike Johnson',
    authorRole: 'SUPPORT_AGENT',
    body: 'Found the issue — a recent configuration change caused the login service to fail. Working on a fix now.',
    createdAt: daysAgo(3),
  },
  {
    id: 'cmt-004',
    ticketId: 'tkt-002',
    authorId: 'usr-002',
    authorName: 'Jane Smith',
    authorRole: 'USER',
    body: 'The dashboard loads very slowly, sometimes taking 10+ seconds.',
    createdAt: daysAgo(3),
  },
  {
    id: 'cmt-005',
    ticketId: 'tkt-002',
    authorId: 'usr-004',
    authorName: 'Sarah Williams',
    authorRole: 'SUPPORT_AGENT',
    body: 'I will look into the performance issue. Can you share which browser you are using?',
    createdAt: daysAgo(2),
  },
];

export const mockTickets: Ticket[] = [
  {
    id: 'tkt-001',
    ticketNumber: 'TKT-2025-001',
    title: 'Unable to log in after password reset',
    description:
      'After resetting my password, I am unable to log in to my account. The system shows an error message saying "Authentication failed" even though I am using the new password. I have tried clearing my cache and using a different browser, but the issue persists.',
    category: 'ACCOUNT',
    priority: 'HIGH',
    status: 'IN_PROGRESS',
    requesterId: 'usr-001',
    requesterName: 'John Doe',
    assignedAgentId: 'usr-003',
    assignedAgentName: 'Mike Johnson',
    comments: mockComments.filter((c) => c.ticketId === 'tkt-001'),
    createdAt: daysAgo(5),
    updatedAt: daysAgo(3),
  },
  {
    id: 'tkt-002',
    ticketNumber: 'TKT-2025-002',
    title: 'Dashboard loading extremely slowly',
    description:
      'The main dashboard takes over 10 seconds to load. This started happening about two days ago and is affecting my productivity significantly.',
    category: 'TECHNICAL',
    priority: 'MEDIUM',
    status: 'OPEN',
    requesterId: 'usr-002',
    requesterName: 'Jane Smith',
    assignedAgentId: 'usr-004',
    assignedAgentName: 'Sarah Williams',
    comments: mockComments.filter((c) => c.ticketId === 'tkt-002'),
    createdAt: daysAgo(3),
    updatedAt: daysAgo(2),
  },
  {
    id: 'tkt-003',
    ticketNumber: 'TKT-2025-003',
    title: 'Billing charge appears twice on my invoice',
    description:
      'My latest invoice shows the same charge listed twice. I was only supposed to be charged once for the premium plan.',
    category: 'BILLING',
    priority: 'URGENT',
    status: 'OPEN',
    requesterId: 'usr-001',
    requesterName: 'John Doe',
    assignedAgentId: null,
    assignedAgentName: null,
    comments: [],
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: 'tkt-004',
    ticketNumber: 'TKT-2025-004',
    title: 'Feature request: Dark mode for mobile app',
    description:
      'It would be great to have a dark mode option in the mobile application, especially for evening use.',
    category: 'FEATURE_REQUEST',
    priority: 'LOW',
    status: 'OPEN',
    requesterId: 'usr-002',
    requesterName: 'Jane Smith',
    assignedAgentId: null,
    assignedAgentName: null,
    comments: [],
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
  },
  {
    id: 'tkt-005',
    ticketNumber: 'TKT-2025-005',
    title: 'Export to CSV button not working',
    description:
      'When I click the Export to CSV button on the reports page, nothing happens. No file downloads and no error message appears.',
    category: 'BUG_REPORT',
    priority: 'MEDIUM',
    status: 'IN_PROGRESS',
    requesterId: 'usr-001',
    requesterName: 'John Doe',
    assignedAgentId: 'usr-003',
    assignedAgentName: 'Mike Johnson',
    comments: [],
    createdAt: daysAgo(4),
    updatedAt: daysAgo(2),
  },
  {
    id: 'tkt-006',
    ticketNumber: 'TKT-2025-006',
    title: 'Cannot update profile picture',
    description:
      'Every time I try to upload a new profile picture, I get an error saying the file is too large, even though it is under the stated size limit.',
    category: 'TECHNICAL',
    priority: 'LOW',
    status: 'RESOLVED',
    requesterId: 'usr-002',
    requesterName: 'Jane Smith',
    assignedAgentId: 'usr-004',
    assignedAgentName: 'Sarah Williams',
    comments: [],
    createdAt: daysAgo(7),
    updatedAt: daysAgo(5),
  },
  {
    id: 'tkt-007',
    ticketNumber: 'TKT-2025-007',
    title: 'API returns 500 error on specific endpoint',
    description:
      'The /api/v1/reports endpoint returns a 500 Internal Server Error when filtering by date range longer than 30 days.',
    category: 'BUG_REPORT',
    priority: 'HIGH',
    status: 'IN_PROGRESS',
    requesterId: 'usr-001',
    requesterName: 'John Doe',
    assignedAgentId: 'usr-003',
    assignedAgentName: 'Mike Johnson',
    comments: [],
    createdAt: daysAgo(3),
    updatedAt: daysAgo(1),
  },
  {
    id: 'tkt-008',
    ticketNumber: 'TKT-2025-008',
    title: 'Account locked after too many login attempts',
    description:
      'My account got locked after I mistyped my password a few times. I need it unlocked to access my work.',
    category: 'ACCOUNT',
    priority: 'HIGH',
    status: 'CLOSED',
    requesterId: 'usr-002',
    requesterName: 'Jane Smith',
    assignedAgentId: 'usr-004',
    assignedAgentName: 'Sarah Williams',
    comments: [],
    createdAt: daysAgo(10),
    updatedAt: daysAgo(8),
  },
  {
    id: 'tkt-009',
    ticketNumber: 'TKT-2025-009',
    title: 'Email notifications not arriving',
    description:
      'I have not received any email notifications for the past week, even though my notification settings are enabled.',
    category: 'GENERAL',
    priority: 'MEDIUM',
    status: 'OPEN',
    requesterId: 'usr-001',
    requesterName: 'John Doe',
    assignedAgentId: null,
    assignedAgentName: null,
    comments: [],
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: 'tkt-010',
    ticketNumber: 'TKT-2025-010',
    title: 'Two-factor authentication setup fails',
    description:
      'When I try to enable 2FA, the QR code does not appear and the setup process hangs indefinitely.',
    category: 'ACCOUNT',
    priority: 'URGENT',
    status: 'IN_PROGRESS',
    requesterId: 'usr-002',
    requesterName: 'Jane Smith',
    assignedAgentId: 'usr-003',
    assignedAgentName: 'Mike Johnson',
    comments: [],
    createdAt: daysAgo(2),
    updatedAt: now,
  },
];

export const statusTransitions: Record<TicketStatus, TicketStatus[]> = {
  OPEN: ['IN_PROGRESS'],
  IN_PROGRESS: ['RESOLVED'],
  RESOLVED: ['OPEN', 'CLOSED'],
  CLOSED: ['OPEN'],
};

export const priorityLevels: TicketPriority[] = ['LOW', 'MEDIUM', 'HIGH', 'URGENT'];
